export { default as Home } from "./Home/Home";
export { default as About } from "./About/About";
export { default as Login } from "./Login/Login";
export { default as Account } from "./Account/Account";
export { default as Setup } from "./Setup/Setup";
export { default as Privacy } from "./Privacy/Privacy";
export { default as Upload } from "./Upload/Upload";
export { default as Terms } from "./Terms/Terms";
export { default as Contact } from "./Contact/Contact";